# can be overridden by profiles
ansible_connection: local
ansible_become: yes
ansible_become_method: runas

user_home: "{{ ansible_env.USERPROFILE | default(ansible_env.HOME) }}"
appdata: "{{ ansible_env.APPDATA }}"
localappdata: "{{ ansible_env.LOCALAPPDATA }}"

min_disk_space_gb: 50
min_memory_gb: 8
