---

all:
  hosts:
    windows:
      ansible_host: 127.0.0.1
      ansible_port: 22
      ansible_connection: ssh
      ansible_shell_type: powershell
      ansible_become_method: runas
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
